// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqewuevqfywdilwsgigw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xZXd1ZXZxZnl3ZGlsd3NnaWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTUzNjcsImV4cCI6MjA2MDEzMTM2N30.Nn4KTn7vVM0x_65T1m9CWLnDZPL4Nvp4OC5i8JG2KIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);